-- ─────────────────────────────────────────────
-- TIPS TABLE CREATION
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tips (
  id_tips BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  category VARCHAR(100) NOT NULL,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_tips_category ON tips(category);
CREATE INDEX IF NOT EXISTS idx_tips_is_active ON tips(is_active);
CREATE INDEX IF NOT EXISTS idx_tips_sort_order ON tips(sort_order);

-- ─────────────────────────────────────────────
-- SAMPLE DATA FOR TIPS
-- ─────────────────────────────────────────────
INSERT INTO tips (title, description, category, sort_order, is_active)
VALUES
  (
    '5 Teknik Napas Redakan Panik',
    'Latihan pernapasan dalam terbukti menurunkan detak jantung dan kecemasan dalam beberapa menit.',
    'Relaksasi',
    1,
    true
  ),
  (
    'Hindari Gadget Sebelum Tidur',
    'Paparan layar menghambat produksi hormon tidur (melatonin). Hentikan penggunaan gadget 1 jam sebelum tidur untuk kualitas tidur lebih baik.',
    'Tidur Sehat',
    1,
    true
  ),
  (
    'Teknik Pomodoro untuk Belajar',
    'Belajar 25 menit lalu istirahat 5 menit terbukti meningkatkan konsentrasi dan produktivitas. Setelah 4 siklus, ambil istirahat lebih lama 15-30 menit.',
    'Fokus Belajar',
    1,
    true
  ),
  (
    'Meditasi 5 Menit Setiap Pagi',
    'Meditasi singkat di pagi hari membantu menenangkan pikiran dan menyiapkan mental lebih positif untuk menghadapi hari.',
    'Relaksasi',
    2,
    true
  ),
  (
    'Jadwal Tidur Konsisten',
    'Tidur dan bangun di jam yang sama setiap hari membantu ritme sirkadian tubuhmu. Konsistensi ini meningkatkan kualitas tidur secara signifikan.',
    'Tidur Sehat',
    2,
    true
  ),
  (
    'Catat dengan Metode Cornell',
    'Metode pencatatan terstruktur membantu otak memproses dan mengingat informasi lebih efektif. Bagi halaman catatan menjadi 3 bagian: catatan, clue, dan rangkuman.',
    'Fokus Belajar',
    2,
    true
  ),
  (
    'Stretching untuk Relaksasi Otot',
    'Gerakan stretching ringan selama 5-10 menit dapat mengurangi ketegangan otot dan meningkatkan sirkulasi darah untuk relaksasi tubuh.',
    'Relaksasi',
    3,
    true
  ),
  (
    'Ciptakan Lingkungan Belajar yang Tenang',
    'Lingkungan belajar yang tenang dan rapi meningkatkan fokus hingga 40%. Jauhkan distraksi seperti ponsel dan matikan notifikasi.',
    'Fokus Belajar',
    3,
    true
  );
